LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = mtk-ril
LOCAL_MODULE_CLASS = SHARED_LIBRARIES
LOCAL_MODULE_OWNER = mtk
LOCAL_MODULE_SUFFIX = .so
LOCAL_PROPRIETARY_MODULE = true
LOCAL_SHARED_LIBRARIES_64 = libnetutils librilmtk libc++
LOCAL_MULTILIB = 64
LOCAL_SRC_FILES_64 = arm64/mtk-ril.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE = mtk-ril
LOCAL_MODULE_CLASS = SHARED_LIBRARIES
LOCAL_MODULE_OWNER = mtk
LOCAL_MODULE_SUFFIX = .so
LOCAL_PROPRIETARY_MODULE = true
LOCAL_SHARED_LIBRARIES = libnetutils librilmtk libc++
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 = arm/mtk-ril.so
include $(BUILD_PREBUILT)
