LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = libmp4enc_xa.ca7
LOCAL_MODULE_CLASS = SHARED_LIBRARIES
LOCAL_MODULE_OWNER = mtk
LOCAL_MODULE_SUFFIX = .so
LOCAL_PROPRIETARY_MODULE = true
LOCAL_MODULE_TAGS = optional
LOCAL_SHARED_LIBRARIES = libvcodec_utility libvcodec_oal libstdc++
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 = arm/libmp4enc_xa.ca7.so
include $(BUILD_PREBUILT)
