LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = libSwJpgCodec
LOCAL_MODULE_CLASS = SHARED_LIBRARIES
LOCAL_MODULE_OWNER = mtk
LOCAL_MODULE_SUFFIX = .so
LOCAL_PROPRIETARY_MODULE = true
LOCAL_MODULE_TAGS = eng
LOCAL_SHARED_LIBRARIES = libmtkjpeg libc++
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 = arm/libSwJpgCodec.so
include $(BUILD_PREBUILT)
