LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = ged_srv
LOCAL_MODULE_CLASS = EXECUTABLES
LOCAL_MODULE_OWNER = mtk
LOCAL_PROPRIETARY_MODULE = true
LOCAL_SHARED_LIBRARIES = libged libbinder libui libgui libgas libc++
LOCAL_MULTILIB = 64
LOCAL_SRC_FILES_64 = arm64/ged_srv
include $(BUILD_PREBUILT)
