LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = md_ctrl
LOCAL_MODULE_CLASS = EXECUTABLES
LOCAL_MODULE_OWNER = mtk
LOCAL_PROPRIETARY_MODULE = true
LOCAL_SHARED_LIBRARIES = liblogwrap libc++
LOCAL_MULTILIB = 64
LOCAL_SRC_FILES_64 = arm64/md_ctrl
include $(BUILD_PREBUILT)
