LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = libbt-vendor
LOCAL_MODULE_CLASS = SHARED_LIBRARIES
LOCAL_MODULE_OWNER = mtk
LOCAL_MODULE_SUFFIX = .so
LOCAL_PROPRIETARY_MODULE = true
LOCAL_MODULE_TAGS = optional
LOCAL_SHARED_LIBRARIES = libbluetooth_mtk libc++
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 = arm/libbt-vendor.so
include $(BUILD_PREBUILT)
